# Generated by Django 3.0.8 on 2021-01-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.TextField()),
                ('name', models.TextField()),
                ('relationship', models.TextField()),
                ('mobile', models.TextField()),
            ],
        ),
    ]
